
###
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json


{
    "correo": "usernica25@yahoo.es",
    "password": "1234567"
}

 
###
GET http://localhost:8080/api/productos HTTP/1.1

###
GET http://localhost:8080/api/productos?limite=2&desde=4 HTTP/1.1

###
GET http://localhost:8080/api/productos/662734ae4da7622bd4874963 HTTP/1.1
 
###
POST http://localhost:8080/api/productos/ HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NjE0YzI3ZTc4MDExNTY5ZmQwZWVjNTMiLCJpYXQiOjE3MTM4OTA5NzEsImV4cCI6MTcxMzkwNTM3MX0.Az9_ps6YPffJDJ1DU0qknrfl_d9E7dZpd414x2kErB4
Content-Type: application/json


{
    "nombre": "Nachos Fritos",
    "categoria": "6625a3b57713f13ef4b0eaf9"

}

###
PUT http://localhost:8080/api/productos/662735684da7622bd4874984 HTTP/1.1
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NjE0YzI3ZTc4MDExNTY5ZmQwZWVjNTMiLCJpYXQiOjE3MTM4NDA4NzMsImV4cCI6MTcxMzg1NTI3M30.5D5T8311r8TnYmDQss6yAWjdz1cYe89qAqgiZrJy_6g


{
    "nombre": "CHIKI Update"
}

###
DELETE http://localhost:8080/api/productos/662735334da7622bd487497a HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NjE0YzI3ZTc4MDExNTY5ZmQwZWVjNTMiLCJpYXQiOjE3MTM4NDA4NzMsImV4cCI6MTcxMzg1NTI3M30.5D5T8311r8TnYmDQss6yAWjdz1cYe89qAqgiZrJy_6g