
###
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json


{
    "correo": "usernica25@yahoo.es",
    "password": "1234567"
}

 
###
GET http://localhost:8080/api/buscar/usuarios/6614c00227988e493fa80eb6 HTTP/1.1

###
GET http://localhost:8080/api/buscar/usuarios/User 3 HTTP/1.1


###
GET http://localhost:8080/api/buscar/categorias/CHICLES HTTP/1.1

###
GET http://localhost:8080/api/buscar/productos/papas HTTP/1.1